### PR TITLE
Readme: use correct highlighter for the yaml block

### PR DESCRIPTION
**Pull request by bfred-it**
Related to #63

### CODE REVIEW

**Comment by kentcdodds** [comment]
Excellent! 👍 :shipit:

**Comment by kentcdodds** [comment]
Do you wanna [add yourself as a docs contributor](https://github.com/kentcdodds/p-s/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)?

**Comment by bfred-it** [comment]
Unless it's necessary I'll pass. It's too minor :)

**Comment by kentcdodds** [comment]
Nothing's too minor. Thanks for caring enough to contribute!

**Comment by sxn** [comment]
Whoops. Thanks! :)

**Pull request merged**
