### PR TITLE
docs(contributors): Add nkbt to contributors list

### PR DESCRIPTION
**Pull request by nkbt**
**What**: Add myself to contributors list

**Why**: Contributed to docs

### CODE REVIEW

**Comment by jfmengels** [comment]
You need to add yourself as a contributor by following this [guide](https://github.com/kentcdodds/p-s/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor). It will update the `.all-contributorsrc` file, which is used to generate the contributors list later on (otherwise you'll be removed next time the list gets updated).
Sorry you had to go through the process of manually adding yourself :s

**Comment by kentcdodds** [comment]
Yup, what @jfmengels said

**Comment by nkbt** [comment]
Sure, but honestly, who reads readmes? 😜

**Comment by nkbt** [comment]
Fixed.

**Comment by kentcdodds** [comment]
LGTM

**Pull request merged**
