### PR TITLE
docs(README): fix mentions of `npm start` alias (closes #80)

### LINKED ISSUE #80: Possible error in readme (npm run start === nps)
- `p-s` version: 3.0.3
- `node` version: 6.9.1
- `npm` version: 3.10.8

Scripts file (or at least the relevant bits): N/A

The command executed:

```console
$ nps
```

The output:

```console
-bash: nps: command not found
```

Problem description:

The README claims that `npm run start` is equivalent to `nps`:

> npm scripts are generally run with `npm run <script-name>`. There are some exceptions to
this. For example:
>
> 1. `npm run test` === `npm test` === `npm t`
> 2. `npm run start` === `nps`
>
> So, while you could use a script called `script` and run `npm run script build`, I just think it reads more clearly to
> just use the `start` script and run `nps build`.

However, this does not appear to be true (at least in my version of npm)... the only built-in start alias I'm aware of is `npm run start` === `npm start`.

Suggested solution:

I'll issue a PR right after submitting this =)

### PR DESCRIPTION
**Pull request by msegado**
**What**: Possible typo in README (see #80)

**Why**: Avoids confusion for new users if it is indeed a typo

**How**: Changed the text in a couple of places... see diff. (Note though, I might have missed other places that need the change since I didn't read through in too much detail.)

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ah! Thank you! That was definitely a copy/paste bug :)

Would you like to [add yourself as a contributor](https://github.com/kentcdodds/p-s/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)?

:shipit:

**Comment by msegado** [comment]
Haha, sure! =) Will push that in a second. Should I squash the commits myself or leave that to you?

**Comment by kentcdodds** [comment]
You can leave squashing to me. GitHub's merging UI is sooooo awesome now :)

**Comment by kentcdodds** [comment]
Thanks for the contribution!

**Comment by msegado** [comment]
Very welcome - thanks for the project!

**Pull request merged**
