### PR TITLE
Fixes version in package.json

### PR DESCRIPTION
**Pull request by martellaj**
**What**: Fixes the "with a missing config" test in **cli.test.js**.

**Why**: The CLI tests are run when you `npm start validate` (which you tell people to do to make sure they're good to go when contributing) and without this change that script fails because of the failing test. I think it's a put-off for someone looking to help out on a project. You also have the failing build badge in your README and I want to see that be green! :)

**How**: The approach I took was to import **package.json** so I can get the current version number of the package (doesn't require you to update the test every time you release a new patch or version) and then replace that value in the error message the test expects with the text expected in your snapshot.

I tried sticking to your coding conventions as much as possible. Feel free to nit about style or update the PR yourself if you'd prefer. Project looks really cool!

### CODE REVIEW

**Comment by martellaj** [comment]
In response to issue #78.

**Comment by martellaj** [comment]
That's a much simpler fix. :smile: I've gone ahead and done that since the PR is open any case. Hoping to make some more meaningful contributions in the future!

**Comment by kentcdodds** [comment]
:shipit:

**Comment by kentcdodds** [comment]
You can now squash and merge this yourself! (Please make sure the commit message for the squashed commit if correct, all me if you have questions).
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the CONTRIBUTING.md file (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by martellaj** [comment]
Sounds great, man. Looking forward to digging into this project more and getting more involved with OSS!

**Comment by kentcdodds** [comment]
Awesome! Thanks 😀

**Pull request merged**
